matrix:
  include:
    - language: node_js
      node_js:
        - '7'
      cache: npm
      before_install:
        - cd Frontend/
        - npm install
      script:
        - npm run build
      deploy:
        provider: heroku
        app: cooperator-web-frontend-260
        api_key:
          secure: slX9QBmQr5XYjhFuLMlmUZBg0kdXoUqXF9W9Je4Nwb4fySeV3cZuarDJEvoLkI2Y0JEH+0nupj0LbmDuYUl6ag61yffte0NLorm2zJgK7w/PZBpQo5ooLlT2t9j9i3EZdfZfN9qveHO9sSfVWs2KRrgMXMAtuteqn9bhV4mfTEtrcBg7OjNpL5gVdiHUDpgmlJVBIIoXf7rEslP1DGYRrUvjjoLoFK76Mgavg60f5X++epgY1KB8X4OMNAsnUT6puRChXYUS9nnVAdRW1qmWLJv65AuotgucS4Nm8bFscm6VaXr1xckvFkKFuT4CXzMJuerfZn7UR+QgIiNrttsV+5v4v7GMIo5kCdF4zTiMvJzWQqLbm8SCcjsT38z0Wa3TGXdVZ0mY1PuG6YNsZ0ndcvRMjMQ66wT/pBdiktLSc0RKzwItmX4NNPx5r5b38VA7scMwHgjiHTc+LxC9blSSkDPHXVVMnrFjWbWEy8fjvXwIKuNSv4HgWSLzcvyaLMzFXJ7gb07pCOBId4DvvVc6YcAVmaJsPcK3LxbrVFTUo1HoRqkYgF6ZfMHSNMIa2Zx5ze73JpH/Hv06/c1KAvG8mCumyiJn+yIjJHR2QDY4dw3MzURbZKLyz9IvXvW9vJpzNI+4Gecmt1XNoxsKBphW3tpK9cYxkMRerFlrnjWEAxs=
        on:
          branch: akaba/fixFrontEndBuild
    - language: java
      script:
        - "./gradlew build"
      deploy:
        provider: heroku
        app: cooperator-backend-260
        api_key:
          secure: slX9QBmQr5XYjhFuLMlmUZBg0kdXoUqXF9W9Je4Nwb4fySeV3cZuarDJEvoLkI2Y0JEH+0nupj0LbmDuYUl6ag61yffte0NLorm2zJgK7w/PZBpQo5ooLlT2t9j9i3EZdfZfN9qveHO9sSfVWs2KRrgMXMAtuteqn9bhV4mfTEtrcBg7OjNpL5gVdiHUDpgmlJVBIIoXf7rEslP1DGYRrUvjjoLoFK76Mgavg60f5X++epgY1KB8X4OMNAsnUT6puRChXYUS9nnVAdRW1qmWLJv65AuotgucS4Nm8bFscm6VaXr1xckvFkKFuT4CXzMJuerfZn7UR+QgIiNrttsV+5v4v7GMIo5kCdF4zTiMvJzWQqLbm8SCcjsT38z0Wa3TGXdVZ0mY1PuG6YNsZ0ndcvRMjMQ66wT/pBdiktLSc0RKzwItmX4NNPx5r5b38VA7scMwHgjiHTc+LxC9blSSkDPHXVVMnrFjWbWEy8fjvXwIKuNSv4HgWSLzcvyaLMzFXJ7gb07pCOBId4DvvVc6YcAVmaJsPcK3LxbrVFTUo1HoRqkYgF6ZfMHSNMIa2Zx5ze73JpH/Hv06/c1KAvG8mCumyiJn+yIjJHR2QDY4dw3MzURbZKLyz9IvXvW9vJpzNI+4Gecmt1XNoxsKBphW3tpK9cYxkMRerFlrnjWEAxs=
        on:
          branch: akaba/fixFrontEndBuild