matrix:
  include:
  - language: node_js
    node_js:
    - 10.15
    cache: npm
    before_install:
    - cd Frontend/
    - npm install
    script:
    - npm run build
    deploy:
      provider: heroku
      app: cooperator-web-frontend-260
      api_key:
        secure: FEigLRU8UAMwz5w/W/ME4849UlhWIF39r43gI7hMAkasFogU1gQ/wTmP6lZeGpeV1sd33c4a3Y/H6eHt7/0ioDuykW6LMoXAtHNHcRTo6xOsaT/afnbWaNbyH59WjyVa/k/oEgL6+G8WhrblhKLm+aCRwOyn9/yjnhDcj9NMA9RF5ZDtWvp7qDJPWGcVZtv8a1wfdsywpKnE1h5lyU+7HqKM4CWUUWsu7LSrIIzpa7Jmll5RE4FBDYcLMs49zNx8GK9vId/Ct+9/uay3iWhnewGVUkGKjRT2eBF7pX1N7ejfE102G8KtfyVAZAdYO2+zVZ/bEWRJUh7DT+jYUuEvXL7Oh17UNgT4apfUupMD4ugNJMkZgRBmf1i+6Nm+MER6WDocdc/08/GFSUBkNZu8WtLC+/YCjwUjPDhEZIYx2nPdOCD+fNo5tZVqvGqY4v0k41QHsjpRtB5w5Ipu5vUbBYQWYdnZ1RAdH+L0hYdK+q2j3HEuCHNXSQjtUS9OpESCSzvJL+/6DiAVsUlU30FFr1qlclKjUGME3xG0+VA33lO4RO1lSBJPIgss8SAKGYGLCd39uI1haNzL2bBXJfkagziCS35bukYbRKfOpiKkl0d7phXheOxceHiZ3fPyoqFDTSvoom5JsSWjeKSjI0Vy6fLFjdxRfld2xmk9L1bqqMg
  - language: java
    script:
    - "./gradlew build"
    deploy:
      provider: heroku
      app: cooperator-backend-260
      api_key:
        secure: FEigLRU8UAMwz5w/W/ME4849UlhWIF39r43gI7hMAkasFogU1gQ/wTmP6lZeGpeV1sd33c4a3Y/H6eHt7/0ioDuykW6LMoXAtHNHcRTo6xOsaT/afnbWaNbyH59WjyVa/k/oEgL6+G8WhrblhKLm+aCRwOyn9/yjnhDcj9NMA9RF5ZDtWvp7qDJPWGcVZtv8a1wfdsywpKnE1h5lyU+7HqKM4CWUUWsu7LSrIIzpa7Jmll5RE4FBDYcLMs49zNx8GK9vId/Ct+9/uay3iWhnewGVUkGKjRT2eBF7pX1N7ejfE102G8KtfyVAZAdYO2+zVZ/bEWRJUh7DT+jYUuEvXL7Oh17UNgT4apfUupMD4ugNJMkZgRBmf1i+6Nm+MER6WDocdc/08/GFSUBkNZu8WtLC+/YCjwUjPDhEZIYx2nPdOCD+fNo5tZVqvGqY4v0k41QHsjpRtB5w5Ipu5vUbBYQWYdnZ1RAdH+L0hYdK+q2j3HEuCHNXSQjtUS9OpESCSzvJL+/6DiAVsUlU30FFr1qlclKjUGME3xG0+VA33lO4RO1lSBJPIgss8SAKGYGLCd39uI1haNzL2bBXJfkagziCS35bukYbRKfOpiKkl0d7phXheOxceHiZ3fPyoqFDTSvoom5JsSWjeKSjI0Vy6fLFjdxRfld2xmk9L1bqqMg